### ISSUE TITLE
Version conflict for plexus-utils in Eclipse build

### ISSUE THREAD

**Issue by jsilland** [sergei-ivanov/maven-protoc-plugin#10]
At the demand of a few engineers in my org, I'm trying to integrate the Maven+proto tooling into a working Eclipse build. I've had success getting successful builds at the command line but am struggling to make sense of this issue. It appears there is a version conflict between the various version of plexus-utils on which a lot of plugins rely — maven-protoc-plugin has made the leap to 3.0.10 while the rest of the world uses 2.0.5 or even 1.5.*. The following error output annotates the pom.xml file in Eclipse:

<pre>
Execution Generate proto sources of goal com.google.protobuf.tools:maven-protoc-plugin:0.3.1:compile failed: An API incompatibility was encountered while executing com.google.protobuf.tools:maven-protoc-plugin:0.3.1:compile: java.lang.NoSuchMethodError: org.codehaus.plexus.util.DirectoryScanner.setupMatchPatterns()V
-----------------------------------------------------
realm =    plugin>com.google.protobuf.tools:maven-protoc-plugin:0.3.1
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/Users/jsilland/.m2/repository/com/google/protobuf/tools/maven-protoc-plugin/0.3.1/maven-protoc-plugin-0.3.1.jar
urls[1] = file:/Users/jsilland/.m2/repository/com/google/collections/google-collections/1.0/google-collections-1.0.jar
urls[2] = file:/Users/jsilland/.m2/repository/org/apache/maven/plugin-tools/maven-plugin-annotations/3.2/maven-plugin-annotations-3.2.jar
urls[3] = file:/Users/jsilland/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.10/plexus-utils-3.0.10.jar
urls[4] = file:/Users/jsilland/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
urls[5] = file:/Users/jsilland/.m2/repository/backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.jar
urls[6] = file:/Users/jsilland/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.11/plexus-interpolation-1.11.jar
urls[7] = file:/Users/jsilland/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar
urls[8] = file:/Users/jsilland/.m2/repository/org/slf4j/slf4j-jdk14/1.5.6/slf4j-jdk14-1.5.6.jar
urls[9] = file:/Users/jsilland/.m2/repository/org/slf4j/slf4j-api/1.5.6/slf4j-api-1.5.6.jar
urls[10] = file:/Users/jsilland/.m2/repository/org/slf4j/jcl-over-slf4j/1.5.6/jcl-over-slf4j-1.5.6.jar
urls[11] = file:/Users/jsilland/.m2/repository/org/apache/maven/reporting/maven-reporting-api/2.2.1/maven-reporting-api-2.2.1.jar
urls[12] = file:/Users/jsilland/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.1/doxia-sink-api-1.1.jar
urls[13] = file:/Users/jsilland/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.1/doxia-logging-api-1.1.jar
urls[14] = file:/Users/jsilland/.m2/repository/commons-cli/commons-cli/1.2/commons-cli-1.2.jar
urls[15] = file:/Users/jsilland/.m2/repository/org/codehaus/plexus/plexus-interactivity-api/1.0-alpha-4/plexus-interactivity-api-1.0-alpha-4.jar
urls[16] = file:/Users/jsilland/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
urls[17] = file:/Users/jsilland/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
urls[18] = file:/Users/jsilland/.m2/repository/org/sonatype/aether/aether-util/1.13.1/aether-util-1.13.1.jar
Number of foreign imports: 4
import: Entry[import org.sonatype.plexus.build.incremental from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.util.Scanner from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.util.AbstractScanner from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------
 (com.google.protobuf.tools:maven-protoc-plugin:0.3.1:compile:Generate proto sources:generate-sources)
</pre>

And indeed, that particular method (protected setupMatchPatterns) is new in plexus v3. I've reached a functional state by forcing down the version of plexus-utils in the maven-protoc-plugin deps. I guess there might be some different way of solving this issue but my investigation has failed to find another way:

<pre>
            &lt;plugin&gt;
                &lt;groupId&gt;com.google.protobuf.tools&lt;/groupId&gt;
                &lt;artifactId&gt;maven-protoc-plugin&lt;/artifactId&gt;
                &lt;version&gt;0.3.1&lt;/version&gt;
                &lt;dependencies&gt;
                    &lt;dependency&gt;
                        &lt;groupId&gt;org.codehaus.plexus&lt;/groupId&gt;
                        &lt;artifactId&gt;plexus-utils&lt;/artifactId&gt;
                        &lt;version&gt;2.0.5&lt;/version&gt;
                    &lt;/dependency&gt;
                &lt;/dependencies&gt;
            &lt;/plugin&gt;
</pre>

Is there another way besides sprinkling this all over my projects?

**Comment by sergei-ivanov** [comment]
An update.

The latest plugin version 0.4.0 broke Eclipse again for the same reason, but this time we got to the bottom of it. There was a critical bug in M2E that prevented it from working with a number of code-generating Maven plugins, including the protobuf plugin.
https://bugs.eclipse.org/bugs/show_bug.cgi?id=422106

The bug was fixed in M2E 1.5, and you may need to update Eclipse to use that bundle. You **do not need** to update Eclipse Luna or later, because it should already be using the latest M2E.

In case you are using an older version of Eclipse, or some other IDE that is based on the older version of Eclipse, you need to do the following. You need to go into *Window > Preferences > Install/Update > Available Software Sites* and add the following entries:

Name | URL
------------ | -------------
M2E 1.5 | http://download.eclipse.org/technology/m2e/releases/1.5
Eclipse Luna | http://download.eclipse.org/releases/luna/

It then takes an awful lot of time to pull down the update config from the internet.
Then you invoke *Help > Check for Updates*, tick M2E and go through the wizard steps.
Then it takes an awful lot of time to pull down the latest M2E and its dependencies.
Then you need to restart the IDE and wait for almost an eternity.
Eventually it will finish updating, rebuilding, refreshing and whatever else it also fancies doing, and you’ll be in a pretty good state to carry on with your development.
