### ISSUE TITLE
Plugin repository is busted 

### ISSUE THREAD

**Issue by praste** [sergei-ivanov/maven-protoc-plugin#29]
http://sergei-ivanov.github.com/maven-protoc-plugin/repo/releases/
returns 404

**Comment by sergei-ivanov** [comment]
Please see #23 
It is a known issue, but the files are actually there. At the moment, I am working on a new release that fixes compatibility problems with the latest Maven. I hope it is going to be the latest release from this fork, because I'd like to start a clean development and do it properly, with releases to Maven central (which I cannot do because of licensing issues with this fork).

**Comment by sergei-ivanov** [comment]
Hi,

I've also uploaded the artifacts to bintray, please see the latest README for instructions.

Sergei
