### ISSUE TITLE
Protoc is now available in the central repository

### ISSUE THREAD

**Issue by osechet** [sergei-ivanov/maven-protoc-plugin#33]
Protoc is now available in the central repository as com.google.protobuf:protoc:2.6.1. Do you think it would be possible to use it in the plugin to avoid the configuration of the protoc path?

**Comment by sergei-ivanov** [comment]
Hi,

Yes, I am aware of that, please see the following discussion:
https://github.com/grpc/grpc-java/issues/71#issuecomment-94948836

I need a spare evening to complete the changes to the plugin (about 90% done) and write integration tests and documentation for that case (0% done). Ideally, I would like to wait until `grpc` binaries are available in Maven central too, so that I could test artifact resolution for native protoc plugins too.

Watch this space.

Sergei
